# Generated by Django 4.2.13 on 2024-06-23 12:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ibsapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageform',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
