# Generated by Django 4.2.13 on 2024-06-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibsapi', '0002_homepageform_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageform',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
