# Generated by Django 4.2.13 on 2024-06-23 12:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ibsapi', '0004_homepageform_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepageform',
            name='datetime',
        ),
        migrations.AddField(
            model_name='homepageform',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
