# Generated by Django 4.2.13 on 2024-06-23 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ibsapi', '0005_remove_homepageform_datetime_homepageform_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepageform',
            name='date',
        ),
        migrations.RemoveField(
            model_name='homepageform',
            name='time',
        ),
        migrations.AddField(
            model_name='homepageform',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
